apiVersion: apps/v1
kind: Deployment
metadata:
  name: qp-storage
  namespace: qp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qp-storage
  template:
    metadata:
      labels:
        app: qp-storage
    spec:
      containers:
      - image: "||registry||/qp8-cms/storage:||version||"
        name: qp-storage
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /app/wwwroot
          name: library-volume
        resources: 
          limits:
            memory: "128Mi"
      volumes:
      - name: library-volume
        persistentVolumeClaim:
          claimName: qp-library
---
apiVersion: v1
kind: Service
metadata:
  name: qp-storage
  namespace: qp
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: qp-storage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: qp-storage
  namespace: qp
spec:
  rules:
  - host: "||host||"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qp-storage
            port:
              number: 80            
